# We install Python with mise, so this should be executed after the mise role.
#
# @see https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
- name:
  ansible.builtin.shell:

- name: Get pip path
  ansible.builtin.shell:
    cmd: mise where python
  register: python_dir

- name: Install Python packages
  ansible.builtin.pip:
    executable: "{{ python_dir.stdout }}/bin/pip"
    name:
      - aws-google-auth       # Tool to generate Google OAuth2 access tokens for AWS STS
      - aws-google-auth[u2f]
      - aws-shell             # Integrated shell for working with the AWS CLI
      - buku                  # CLI Bookmark Manager - https://github.com/jarun/buku
      - cmake-language-server # @see https://github.com/regen100/cmake-language-server
      - cryptography
      - PyGObject
      - pyopenssl
      - rply
      - yubikey-manager
    state: present
