[bootstrap.packages]
"apt:apt-file" = "latest"
"apt:apt-transport-https" = "latest"
"apt:autoconf" = "latest"
"apt:automake" = "latest"
"apt:bash-completion" = "latest"
"apt:bison" = "latest"              # Linux Kernel compilation
"apt:build-essential" = "latest"
"apt:ca-certificates" = "latest"
"apt:cargo" = "latest"
"apt:cifs-utils" = "latest"
"apt:clang" = "latest"
"apt:cmake" = "latest"
"apt:cpu-checker" = "latest"
"apt:curl" = "latest"
"apt:devscripts" = "latest"         # Linux Kernel compilation
"apt:dunst" = "latest"              # Lightweight notification daemon
"apt:etherwake" = "latest"
"apt:fakeroot" = "latest"           # Linux Kernel compilation
"apt:feh" = "latest"                # Lightweight image viewer
"apt:ffmpeg" = "latest"
"apt:flatpak" = "latest"
"apt:flex" = "latest"               # Linux Kernel compilation
"apt:g++" = "latest"
"apt:gcc" = "latest"
"apt:git" = "latest"
"apt:git-secrets" = "latest"        # Prevents you from committing secrets and credentials into git repositories
"apt:gnupg" = "latest"
"apt:groff" = "latest"
"apt:guestfs-tools" = "latest"
"apt:gvfs-backends" = "latest"      # Required for Thunar trash, removable media and remote file systems support
"apt:gvfs-fuse" = "latest"          # Required for Thunar trash, removable media and remote file systems support
"apt:hwinfo" = "latest"
"apt:ipcalc" = "latest"
"apt:libarchive-tools" = "latest"
"apt:libcairo2-dev" = "latest"
"apt:libdbus-1-dev" = "latest"      # Required by the 'dbus-python' package
"apt:libelf-dev" = "latest"         # Linux kernel compilation
"apt:libfontconfig1-dev" = "latest"
"apt:libgirepository-2.0-dev" = "latest"
"apt:libnotify-bin" = "latest"      # For the 'notify-send' command
"apt:libnss3-tools" = "latest"      # Required by the 'mkcert' tool
"apt:libosinfo-bin" = "latest"
"apt:libpcsclite-dev" = "latest"
"apt:libssl-dev" = "latest"         # Linux kernel compilation
"apt:libudev-dev" = "latest"
"apt:libusb-1.0-0-dev" = "latest"
"apt:libxcb-xfixes0-dev" = "latest"
"apt:libxkbcommon-dev" = "latest"
"apt:libyaml-dev" = "latest"
"apt:lshw" = "latest"               # HardWare Lister for Linux
"apt:make" = "latest"
"apt:meson" = "latest"
"apt:nasm" = "latest"               # Required for FFMpeg (installed with asdf)
"apt:network-manager" = "latest"
"apt:openssl" = "latest"
"apt:ovmf" = "latest"
"apt:pgpdump" = "latest"
"apt:pkg-config" = "latest"
"apt:podman" = "latest"
"apt:psmisc" = "latest"             # Required for the 'killall' command for example
"apt:python3-pip" = "latest"
"apt:rsync" = "latest"
"apt:shfmt" = "latest"
"apt:smbclient" = "latest"
"apt:swtpm" = "latest"
"apt:texlive-full" = "latest"          # LaTeX distribution
"apt:tuned" = "latest"
"apt:unzip" = "latest"
"apt:vagrant" = "latest"
"apt:wget" = "latest"
"apt:zip" = "latest"

[settings]
experimental = true

[tools]

# Ansible is open-source technology that can perform virtually any IT task and remove complexity from workflows.
#
# @see https://docs.ansible.com/
"pipx:ansible" = "latest"

# Ansible Language Server
#
# @see https://ansible.readthedocs.io/projects/vscode-ansible/als/
"npm:ansible-language-server" = "latest"

# Declarative CLI Version Manager. Unify tool versions in teams, projects, and CI. Easy, painless, and secure.
#
# @see https://aquaproj.github.io/
"github:aquaproj/aqua" = "latest"

# Sync, search and backup shell history with Atuin.
#
# @see https://atuin.sh
"aqua:atuinsh/atuin" = "latest"

# AWK Language Server
#
# @see https://github.com/Beaglefoot/awk-language-server
"npm:awk-language-server" = "latest"

# The official CLI for Amazon Web Services
#
# @see https://aws.amazon.com/cli/
"aqua:aws/aws-cli" = "latest"

# Integrated shell for working with the AWS CLI
#
# @see https://github.com/awslabs/aws-shell
"pipx:aws-shell" = "latest"

# A cat clone with wings
#
# @see https://github.com/sharkdp/bat
"aqua:sharkdp/bat" = "latest"

# Betterleaks scans code, past or present, for secrets.
#
# @see https://github.com/betterleaks/betterleaks
"aqua:betterleaks/betterleaks" = "latest"

# CLI Bookmark Manager - https://github.com/jarun/buku
#
# @see https://github.com/jarun/buku
"pipx:buku" = "latest"

# Password manager for the command line
#
# @see https://github.com/bitwarden
"aqua:bitwarden/clients" = "latest"

# Identity-aware proxy that provides a simple, secure way to access hosts and critical systems on your network.
#
# @see https://github.com/hashicorp/boundary
"aqua:hashicorp/boundary" = "latest"

# Static code analysis tool for infrastructure-as-code
#
# @see https://github.com/bridgecrewio/checkov
"aqua:bridgecrewio/checkov" = "latest"

# CMake LSP Implementation.
#
# @see https://github.com/regen100/cmake-language-server
"pipx:cmake-language-server" = "latest"

# Better project templates
#
# @see https://cookiecutter.readthedocs.io
"pipx:cookiecutter" = "latest"

# Open-source runtime for composable workflows.
#
# @see https://github.com/dagger/dagger
"aqua:dagger/dagger" = "latest"

# A syntax-highlighting pager for git, diff, and grep output
#
# @see https://github.com/dandavison/delta
"aqua:dandavison/delta" = "latest"

# A tool for exploring a Docker image
#
# @see https://github.com/wagoodman/dive
"aqua:wagoodman/dive" = "latest"

# Container Image Linter for Security
#
# @see https://github.com/goodwithtech/dockle
"aqua:goodwithtech/dockle" = "latest"

# A more intuitive version of du in rust
#
# @see https://github.com/bootandy/dust
"aqua:bootandy/dust" = "latest"

# The official CLI for Amazon EKS !
#
# @see https://eksctl.io/
"aqua:eksctl-io/eksctl" = "latest"

# A modern alternative to ls
#
# @see https://github.com/eza-community/eza
"aqua:eza-community/eza" = "latest"

# Database Migrations Made Easy
#
# @see https://flywaydb.org/
"asdf:flyway" = "11.8.2"

# Fuzzy finder
#
# @see https://github.com/junegunn/fzf
"aqua:junegunn/fzf" = "latest"

# The official CLI for Google Cloud Platform
#
# @see https://cloud.google.com/sdk/docs/install
gcloud = "latest"

# Tool for detecting secrets like passwords, API keys, and tokens in git repos, files, and whatever else you wanna throw at it via stdin.
#
# @see https://github.com/gitleaks/gitleaks
"aqua:gitleaks/gitleaks" = "latest"

# Open source GitLab CLI tool
#
# @see https://docs.gitlab.com/editor_extensions/gitlab_cli/
"gitlab:gitlab-org/cli" = "latest"

# Render markdown on the CLI, with pizzazz!
#
# @see https://github.com/charmbracelet/glow
"aqua:charmbracelet/glow" = "latest"

# The Go programming language
#
# @see https://golang.org/
"core:go" = "latest"

# Fast linters runner for Go
#
# @see https://golangci-lint.run/
"aqua:golangci/golangci-lint" = "latest"

# Template renderer which supports a growing list of datasources
#
# @see https://github.com/hairyhenderson/gomplate
"aqua:hairyhenderson/gomplate" = "latest"

# A vulnerability scanner for container images and filesystems.
#
# @see https://github.com/anchore/grype
"aqua:anchore/grype" = "latest"

# Haskell Dockerfile Linter
#
# @see https://github.com/hadolint/hadolint
"aqua:hadolint/hadolint" = "latest"

# The package manager for Kubernetes
#
# @see https://helm.sh/
"aqua:helm/helm" = "latest"

# A documentation generator for Helm charts.
#
# @see https://github.com/norwoodj/helm-docs
"aqua:norwoodj/helm-docs" = "latest"

# Fast, powerful, and flexible hook management for modern development workflows.
#
# @see https://hk.jdx.dev
"aqua:jdx/hk" = "latest"

# The world’s fastest framework for building websites
#
# @see https://gohugo.io/
"aqua:gohugoio/hugo/hugo-extended" = "latest"

# Lightweight Kubernetes
#
# @see https://k3s.io/
"asdf:k3s" = "latest"

# Kubernetes CLI To Manage Your Clusters In Style!
#
# @see https://github.com/derailed/k9s
"aqua:derailed/k9s" = "latest"

# Krew is the package manager for kubectl plugins.
#
# @see https://krew.sigs.k8s.io/
"aqua:kubernetes-sigs/krew" = "latest"

# A kubectl plugin to colorize kubectl output
#
# @see https://github.com/kubecolor/kubecolor
"aqua:kubecolor/kubecolor" = "latest"

# Kubectl
#
# @see https://kubernetes.io/docs/reference/kubectl/
"aqua:kubernetes/kubernetes/kubectl" = "latest"

# Command-line JSON processor
#
# @see https://github.com/jqlang/jq
"aqua:jqlang/jq" = "latest"

# The Lua programming language
#
# @see https://www.lua.org/
lua = "latest"

# A high-performance, S3-compatible object storage solution.
#
# @see https://github.com/minio/minio
"asdf:minio" = "latest"

# A simple tool to make locally-trusted development certificates.
#
# @see https://github.com/FiloSottile/mkcert
"aqua:FiloSottile/mkcert" = "latest"

# MkDocs is a fast, simple and downright gorgeous static site generator that's geared towards building project
# documentation.
#
# @see https://www.mkdocs.org/
"pipx:mkdocs" = "latest"

# Neovim
#
# @see https://neovim.io/
"vfox:mise-plugins/vfox-neovim" = "latest"

# A Docker-compatible CLI for containerd
#
# @see https://github.com/containerd/nerdctl
"aqua:containerd/nerdctl" = "latest"

# Node.js
#
# @see https://nodejs.org/
"core:node" = "latest"

# AI coding agent, built for the terminal.
#
# @see https://github.com/sst/opencode
"aqua:anomalyco/opencode" = "latest"

# Open source Terraform alternative
#
# @see https://opentofu.org/
"aqua:opentofu/opentofu" = "latest"

# Packer
#
# @see https://www.packer.io/
"aqua:hashicorp/packer" = "latest"

# Install and Run Python Applications in Isolated Environments
#
# @see https://github.com/pypa/pipx
"aqua:pypa/pipx" = "latest"

# A configuration as code language with rich validation and tooling.
#
# @see https://github.com/apple/pkl
"aqua:apple/pkl" = "latest"

# Find Kubernetes resources that have been deprecated
#
# @see https://github.com/FairwindsOps/pluto
"aqua:FairwindsOps/pluto" = "latest"

# Fast, disk space efficient package manager
#
# @see https://pnpm.io/
"aqua:pnpm/pnpm" = "latest"

# A tool for managing OCI containers and pods
#
# @see https://podman.io/
"github:containers/podman" = "latest"

# Kubernetes Live Cluster Linter
#
# @see https://github.com/derailed/popeye
"aqua:derailed/popeye" = "latest"

# Python
#
# @see https://www.python.org/
"core:python" = {
  version = "latest",
  # If you need to update or upgrade one library execute the bellow command.
  #
  #     mise install python -f
  #
  postinstall = """
python -m pip install --upgrade --user cryptography \
  cryptography \
  dbus-python \
  mkdocs-material \
  PyGObject \
  pyopenssl \
  rply
"""
}


# rsync for cloud storage
#
# @see https://rclone.org/
"aqua:rclone/rclone" = "latest"

# A framework for managing and maintaining multi-language pre-commit hooks.
#
# @see https://pre-commit.com/
"aqua:pre-commit/pre-commit" = "latest"

# Linter, debugger, and language server for Rego
#
# @see https://github.com/open-policy-agent/regal
"aqua:StyraInc/regal" = "latest"

# Automated dependency updates. Multi-platform and multi-language.
#
# @see https://docs.renovatebot.com/
#
# FIXME: https://github.com/yarnpkg/berry/issues/7182
"npm:renovate" = { version = "latest", trust_policy_excludes = ["@yarnpkg/libzip@3.2.2"] }

# Recursively search directories for a regex pattern
#
# @see https://github.com/BurntSushi/ripgrep
"aqua:BurntSushi/ripgrep" = "latest"

# The Ruby programming language
#
# @see https://www.ruby-lang.org/
"core:ruby" = {
  version = "latest",

  # If you need to update or upgrade one library execute the bellow command.
  #
  #     mise install ruby -f
  #
  postinstall = """
gem install bundler
gem install jekyll
"""
}

# An extremely fast Python linter and code formatter, written in Rust.
#
# @see https://github.com/astral-sh/ruff
"aqua:astral-sh/ruff" = "latest"

# The Rust programming language
#
# @see https://www.rust-lang.org/
"core:rust" = "latest"

# A shell parser, formatter, and interpreter.
#
# @see https://github.com/mvdan/sh
"aqua:mvdan/sh" = "latest"

# A shell script static analysis tool
#
# @see https://github.com/koalaman/shellcheck
"aqua:koalaman/shellcheck" = "latest"

# Cross-shell prompt
#
# @see https://starship.rs
"aqua:starship/starship" = "latest"

# A versatile, feature-rich TOML toolkit.
#
# @see https://taplo.tamasfe.dev/
"aqua:tamasfe/taplo" = "latest"

# Terraform
#
# @see https://www.terraform.io/
"aqua:hashicorp/terraform" = "latest"

# A utility to generate documentation from Terraform modules in various output formats.
#
# @see https://github.com/terraform-docs/terraform-docs
"aqua:terraform-docs/terraform-docs" = "latest"

# TOML Formatter / Linter / Language Server
#
# @see https://github.com/tombi-toml/tombi
"aqua:tombi-toml/tombi" = "latest"

# Tree-sitter is a parser generator tool and an incremental parsing library.
#
# @see https://github.com/tree-sitter/tree-sitter
"npm:tree-sitter-cli" = "latest"

# A comprehensive and versatile security scanner
#
# @see https://github.com/aquasecurity/trivy
"aqua:aquasecurity/trivy" = "latest"

# Source code spell checker.
#
# @see https://github.com/crate-ci/typos
"aqua:crate-ci/typos" = "latest"

# A specification for CLIs
#
# @see https://github.com/jdx/usage
"aqua:jdx/usage" = "latest"

# An extremely fast Python package and project manager, written in Rust.
#
# @see https://github.com/astral-sh/uv
"aqua:astral-sh/uv" = "latest"

# Manage Secrets & Protect Sensitive Data
#
# @see https://www.vaultproject.io/
"aqua:hashicorp/vault" = "latest"

# A lightweight and portable command-line YAML processor
#
# @see https://github.com/mikefarah/yq
"aqua:mikefarah/yq" = "latest"

# Library and command line tool for configuring a YubiKey.
#
# @see https://github.com/Yubico/yubikey-manager
"pipx:yubikey-manager" = "latest"

# Zellij
#
# @see https://github.com/zellij-org/zellij
"aqua:zellij-org/zellij" = "latest"

# A smarter cd command, inspired by z and autojump
#
# @see https://github.com/ajeetdsouza/zoxide
"aqua:ajeetdsouza/zoxide" = "latest"
