---

repos:
  # The revision doesn't get updated manually, check this https://github.com/zricethezav/gitleaks/releases, to see if
  # there are newer versions
  - repo: https://github.com/zricethezav/gitleaks
    rev: v7.6.1
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: scan
        name: Check leaked secrets with scan
        language: script
        entry: scan.sh
        files: ".*"
