#!/usr/bin/env bash

# shellcheck disable=SC1090,SC1091

# WARNING: rights to this file should be 600, by default most Linux distributions use 644 instead which is not ideal.
#
# see https://steflan-security.com/linux-privilege-escalation-exploiting-bashrc/

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth:erasedups

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi


########################################################################################################################
# Aliases
########################################################################################################################

# You may want to put all your additions into a separate file like  ~/.bash_aliases, instead of adding them here
# directly. See /usr/share/doc/bash-doc/examples in the bash-doc package.
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi


########################################################################################################################
# Bash-it
########################################################################################################################

# Path to the bash it configuration
export BASH_IT="${HOME}/.bash_it"

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
#
# see https://github.com/Bash-it/bash-it/wiki/Themes
#  - bakke
#  - bobby
#  - brunton
#  - candy
#  - clean
#  - demula
#  - dos
#  - doubletime
#  - doubletime_multiline
#  - doubletime_multiline_pyonly
#  - dulcie
#  - duru
#  - elixr
#  - emperor
#  - envy
#  - essential
#  - font
#  - gallifrey
#  - githelpers.theme.bash
#  - gitline
#  - hawaii50
#  - iterate
#  - kitsune
#  - liquidprompt
#  - luan
#  - mairan
#  - mbriggs
#  - metal
#  - minimal
#  - modern
#  - modern-t
#  - modern-time
#  - morris
#  - n0qorg
#  - newin
#  - norbu
#  - nwinkler
#  - nwinkler_random_colors
#  - p4helpers.theme.bash
#  - parrot
#  - pete
#  - powerline
#  - powerline-multiline
#  - powerline-naked
#  - powerline-plain
#  - powerturk
#  - primer
#  - pro
#  - pure
#  - purity
#  - rainbowbrite
#  - ramses
#  - rana
#  - redline
#  - rjorgenson
#  - roderik
#  - sexy
#  - simple
#  - sirup
#  - slick
#  - standard
#  - tonka
#  - tonotdo
#  - tylenol
#  - wanelo
#  - zitron
#  - zork
export BASH_IT_THEME='pure'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
# TODO: Use weechat instead
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh


########################################################################################################################
# fzf
########################################################################################################################

# shellcheck disable=SC1091
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
. ~/scripts/z.sh


########################################################################################################################
# Go
########################################################################################################################
export PATH=$PATH:/usr/local/go/bin


########################################################################################################################
# Node.js
########################################################################################################################

# Configure NPM only for the user (prevent to use root access for global installs).
#
# see https://github.com/sindresorhus/guides/blob/main/npm-global-without-sudo.md
mkdir -p "${HOME}/.npm-packages"
NPM_PACKAGES="${HOME}/.npm-packages"

export PATH="$PATH:$NPM_PACKAGES/bin"

# Preserve MANPATH if you already defined it somewhere in your config. Otherwise, fall back to `manpath` so we can
# inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"


########################################################################################################################
# Terraform
########################################################################################################################
complete -C ~/.local/bin/terraform terraform


########################################################################################################################
# Serverless framework
########################################################################################################################
export PATH="$HOME/.serverless/bin:$PATH"


########################################################################################################################
# Utility functions
########################################################################################################################

# Generate a random password
gpw() {
    openssl rand -base64 48 | cut -c1-"${1}";
}


########################################################################################################################
# Various tricks
########################################################################################################################

# Allow Ctrl+Z to work for 'bg' too.
#
# see https://serverfault.com/questions/283678/whats-the-short-cut-for-fg-in-linux#answer-705440
stty susp undef
bind '"\C-z":"fg\015"'
