---
# The APT repository is configured in the '00-apt-repositories.yml' file

- name: Install 'docker' Linux packages
  become: true
  ansible.builtin.package:
    name:
      - containerd.io
      - docker-buildx-plugin
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin

- name: Create the 'docker' group
  become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user '{{ ansible_env.USER }}' to the 'docker' group
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/bash
    group: "{{ ansible_env.USER }}"
    groups: docker
    append: true
    state: present
