---
- name: Create temporary directory to download opencode archive
  ansible.builtin.tempfile:
    state: directory
  register: opencode_tmp_dir

- name: Download opencode archive
  ansible.builtin.get_url:
    url: https://github.com/sst/opencode/releases/download/v0.6.4/opencode-linux-x64.zip
    dest: "{{ opencode_tmp_dir.path }}/opencode-linux-x64.zip"
    mode: "0400"

- name: Verify opencode checksum
  ansible.builtin.command:
    stdin: "516a3f7fc947bbf8411c34250ac6d81b7d88c786efd3d3c4b3750e77a7a58571 opencode-linux-x64.zip"
    cmd: sha256sum --check
    chdir: "{{ opencode_tmp_dir.path }}"
  register: opencode_checksum_verification
  failed_when: "'opencode-linux-x64.zip: OK' not in opencode_checksum_verification.stdout"

- name: Extract opencode archive
  ansible.builtin.unarchive:
    src: "{{ opencode_tmp_dir.path }}/opencode-linux-x64.zip"
    dest: "{{ opencode_tmp_dir.path }}"
    mode: "0700"

- name: Move opencode binary to ~/.local/bin
  ansible.builtin.copy:
    src: "{{ opencode_tmp_dir.path }}/opencode"
    dest: "{{ ansible_env.HOME }}/.local/bin/opencode"
    mode: "0700"

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ opencode_tmp_dir.path }}"
    state: absent
