---
- name: Create temporary directory to download mkcert
  ansible.builtin.tempfile:
    state: directory
  register: mkcert_tmp_dir

- name: Download mkcert binary
  ansible.builtin.get_url:
    url: "https://dl.filippo.io/mkcert/latest?for=linux/amd64"
    dest: "{{ mkcert_tmp_dir.path }}/mkcert"
    mode: "0700"

- name: Move mkcert binary to /usr/local/bin
  ansible.builtin.shell:
    cmd: mv mkcert /usr/local/bin/mkcert
  args:
    chdir: "{{ mkcert_tmp_dir.path }}"
  become: true

- name: Install mkcert Root CA development certificate
  ansible.builtin.shell:
    cmd: "HOME={{ ansible_env.HOME }} mkcert -install"
  become: true

# @see https://github.com/FiloSottile/mkcert/issues/602#issuecomment-2589612997
- name: Change ownership of mkcert Root CA development certificate
  ansible.builtin.shell:
    cmd: "chown {{ ansible_env.USER }} {{ ansible_env.HOME }}/.local/share/mkcert/rootCA*.pem"
  become: true

- name: Create temporary directory to create TLS certificates
  ansible.builtin.tempfile:
    state: directory
  register: certs_tmp_dir

# TLS certificate for imap4d
#
# FIXME: We should find a way to automate the renewal of this certificate
- name: Create a TLS certificate for imap4d
  ansible.builtin.shell:
    cmd: mkcert -cert-file Baptiste_Gaillard_Imap4d.crt -key-file Baptiste_Gaillard_Imap4d.key mail.localhost imap.localhost smtp.localhost
    chdir: "{{ certs_tmp_dir.path }}"
- name: Move TLS certificate for imap4d
  ansible.builtin.copy:
    src: "{{ certs_tmp_dir.path }}/Baptiste_Gaillard_Imap4d.crt"
    dest: "/etc/ssl/certs/Baptiste_Gaillard_Imap4d.crt"
    mode: "0400"
    force: true
  become: true
- name: Move TLS certificate private key for imap4d
  ansible.builtin.copy:
    src: "{{ certs_tmp_dir.path }}/Baptiste_Gaillard_Imap4d.key"
    dest: "/etc/ssl/private/Baptiste_Gaillard_Imap4d.key"
    mode: "0400"
    force: true
  become: true
