---
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    jsonData:
      cacheLevel: High
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
