---
- name: Get Kubernetes last version
  ansible.builtin.uri:
    url: https://storage.googleapis.com/kubernetes-release/release/stable.txt
    return_content: yes
  register: kubernetes_version
  failed_when: kubernetes_version.status != 200 or kubernetes_version.content is not match("^v[0-9]+\\.[0-9]+\\.[0-9]+$")

- name: Create temporary directory to download kubectl
  ansible.builtin.tempfile:
    state: directory
  register: kubectl_tmp_dir

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/{{ kubernetes_version.content }}/bin/linux/amd64/kubectl
    dest: "{{ kubectl_tmp_dir.path }}/kubectl"
    mode: "0755"

- name: Download kubectl checksum
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/{{ kubernetes_version.content }}/bin/linux/amd64/kubectl.sha256
    return_content: yes
  register: kubectl_sha256

- name: Verify kubectl checksum
  ansible.builtin.command:
    stdin: "{{ kubectl_sha256.content }} kubectl"
    cmd: sha256sum --check
    chdir: "{{ kubectl_tmp_dir.path }}"
  register: kubectl_checksum_verification
  failed_when: "'kubectl: OK' not in kubectl_checksum_verification.stdout"

- name: Move kubectl binary to ~/.local/bin
  ansible.builtin.copy:
    src: "{{ kubectl_tmp_dir.path }}/kubectl"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubectl"
    mode: "0700"

- name: Remove temporary directory
  ansible.builtin.file:
    path: "{{ kubectl_tmp_dir.path }}"
    state: absent
