---
# @see https://prometheus-community.github.io/ansible/branch/main/index.html
- name: Install and configure Prometheus
  ansible.builtin.include_role:
    name: prometheus.prometheus.prometheus
  vars:
    prometheus_agent_mode: false
    prometheus_binary_install_dir: /usr/local/bin
    prometheus_config_dir: /etc/prometheus
    prometheus_config_file: etc/prometheus/prometheus.yml.j2
    prometheus_db_dir: /var/lib/prometheus
    prometheus_system_group: prometheus
    prometheus_system_user: prometheus
    prometheus_web_listen_address: 127.0.0.1:9090

# @see https://prometheus-community.github.io/ansible/branch/main/alertmanager_role.html
- name: Install and configure Prometheus AlertManager
  no_log: false
  ansible.builtin.include_role:
    name: prometheus.prometheus.alertmanager
  vars:
    alertmanager_binary_install_dir: /usr/local/bin
    alertmanager_config_dir: /etc/alertmanager
    alertmanager_config_file: etc/alertmanager/alertmanager.yml.j2
    alertmanager_db_dir: /var/lib/alertmanager
    alertmanager_system_group: alertmanager
    alertmanager_system_user: alertmanager
    alertmanager_web_listen_address: 127.0.0.1:9093

# @see https://prometheus-community.github.io/ansible/branch/main/node_exporter_role.html
- name: Install and configure Prometheus Node Exporter
  ansible.builtin.include_role:
    name: prometheus.prometheus.node_exporter
  vars:
    node_exporter_binary_install_dir: /usr/local/bin
    node_exporter_config_dir: /etc/node_exporter
    node_exporter_system_group: node-exp
    node_exporter_system_user: node-exp
    node_exporter_web_listen_address: 127.0.0.1:9100
    node_exporter_enabled_collectors:
      # @see https://github.com/prometheus-community/ansible/pull/156
      - disable-defaults
      - systemd:
          unit-include: "(grafana-server|mailutils-imap4d|prometheus).service"
