# We install Pnpm with mise, so this should be executed after the mise role.
#
# @see https://docs.ansible.com/ansible/latest/collections/community/general/pnpm_module.html

- name: Get pnpm path
  ansible.builtin.shell:
    cmd: "{{ ansible_env.HOME }}/.local/bin/mise where pnpm"
  register: pnpm_dir

- name: Create the '~/.local/share/pnpm' directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/pnpm"
    state: directory
    mode: '0700'

# @see https://www.npmjs.com/package/tree-sitter-cli
- name: Install 'tree-sitter-cli' Node.js packages
  community.general.pnpm:
    executable: "{{ pnpm_dir.stdout }}/pnpm"
    global: true
    name: "tree-sitter-cli"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/share/pnpm"

# @see https://ansible.readthedocs.io/projects/vscode-ansible/als/
- name: Install 'ansible-language-server' Node.js packages
  community.general.pnpm:
    executable: "{{ pnpm_dir.stdout }}/pnpm"
    global: true
    name: "@ansible/ansible-language-server"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/share/pnpm"

# @see https://github.com/Beaglefoot/awk-language-server
- name: Install 'awk-language-server' Node.js packages
  community.general.pnpm:
    executable: "{{ pnpm_dir.stdout }}/pnpm"
    global: true
    name: "awk-language-server"
  environment:
    PNPM_HOME: "{{ ansible_env.HOME }}/.local/share/pnpm"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/share/pnpm"
